language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build finnhub_ruby.gemspec
  - gem install ./finnhub_ruby-1.1.5.gem
