# -*- encoding: utf-8 -*-

=begin
#Finnhub API

#Ruby client for Finnhub API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "finnhub_ruby/version"

Gem::Specification.new do |s|
  s.name        = "finnhub_ruby"
  s.version     = FinnhubRuby::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Finnhub"]
  s.email       = ["support@finnhub.io"]
  s.homepage    = "https://github.com/Finnhub-Stock-API/finnhub-ruby"
  s.summary     = "Finnhub API Ruby Gem"
  s.description = "Ruby client for Finnhub API. Finnhub API provides real-time stock price, crypto, and forex data."
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'json', '~> 2.3'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  s.test_files    = s.files.grep(%r{^(test|spec|features)/})
  s.executables   = []
  s.require_paths = ["lib"]
end
