=begin
#Finnhub API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FinnhubRuby::BondYieldCurveInfo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FinnhubRuby::BondYieldCurveInfo do
  let(:instance) { FinnhubRuby::BondYieldCurveInfo.new }

  describe 'test an instance of BondYieldCurveInfo' do
    it 'should create an instance of BondYieldCurveInfo' do
      expect(instance).to be_instance_of(FinnhubRuby::BondYieldCurveInfo)
    end
  end
  describe 'test attribute "d"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "v"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
