=begin
#Finnhub API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FinnhubRuby::MutualFundsCountryExposure
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FinnhubRuby::MutualFundsCountryExposure do
  let(:instance) { FinnhubRuby::MutualFundsCountryExposure.new }

  describe 'test an instance of MutualFundsCountryExposure' do
    it 'should create an instance of MutualFundsCountryExposure' do
      expect(instance).to be_instance_of(FinnhubRuby::MutualFundsCountryExposure)
    end
  end
  describe 'test attribute "symbol"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "country_exposure"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
